Fix coroutine decorator in the admin CLI (#1803)
`asyncio.coroutine` has been deprecated long enough that it doesn't
exist anymore in python 3.11+ which means that running `uv run
shipit_rebuild_product_details` as given in the documentation failed
with:

```
  File "/home/eijemoz/code/shipit/.venv/bin/shipit_rebuild_product_details", line 4, in <module>
    from shipit_api.admin.cli import rebuild_product_details
  File "/home/eijemoz/code/shipit/api/src/shipit_api/admin/cli.py", line 63, in <module>
    @coroutine
     ^^^^^^^^^
  File "/home/eijemoz/code/shipit/api/src/shipit_api/admin/cli.py", line 31, in coroutine
    coroutine_f = asyncio.coroutine(f)
                  ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```