bustage fix: revert #1586 (#1590)
It looks like this broke in prod for DevEdition :(

https://mozilla.sentry.io/issues/6138643868/?alert_rule_id=14011861&alert_type=issue&notification_uuid=26c35ba9-1f19-46fc-98b1-28e22632153a&project=6262522&referrer=slack

```
ClickException: Too few firefox primary builds for FIREFOX_DEVEDITION
  File "aioamqp/protocol.py", line 312, in run
    await self.dispatch_frame()
  File "aioamqp/protocol.py", line 268, in dispatch_frame
    await channel.dispatch_frame(frame)
  File "aioamqp/channel.py", line 114, in dispatch_frame
    await methods[frame.name](frame)
  File "aioamqp/channel.py", line 546, in basic_deliver
    await callback(self, body, envelope, properties)
  File "/app/src/src/shipit_api/admin/worker.py", line 27, in rebuild_product_details_async
    await rebuild(flask.current_app.db.session, app_channel, git_repo_url, folder_in_repo, breakpoint_version)
  File "/app/src/src/shipit_api/admin/product_details.py", line 1266, in rebuild
    sanity_checks(product_details)
  File "/app/src/src/shipit_api/admin/product_details.py", line 1091, in sanity_checks
    sanity_check_firefox_builds(
  File "/app/src/src/shipit_api/admin/product_details.py", line 1063, in sanity_check_firefox_builds
    raise click.ClickException(f"Too few firefox primary builds for {version_key}")
```